### ISSUE TITLE
File format correlation direction

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#11]
Inputting "Correlation direction" in the Horizons tab: The "Files of type" in the file browser is set to "Correlation file (*storm)" by default, should be the "Surface file (*storm, *irap, *Sgri)".

This should also be fixed for surfaces under Multizone background model, these are said to be "Seismic file" but should be "Surface file"

**Comment by alfbr** [comment]
Please confirm that the bug is fixed.

**Comment by elila** [comment]
Confirmed
