### ISSUE TITLE
Trying to use "Optimize position" results in crash

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#12]
The GUI often crashes with Segmentation fault when clicking "Add Optimization" under "Optimize position for this well" several times. No specific pattern/trigger is found.

**Comment by alfbr** [comment]
Not able to reproduce, please check again.

**Comment by elila** [comment]
I was able to reproduce, but trigger is unknown.

**Comment by elila** [comment]
Reproduced crash by adding three optimizations and deleting the middle one.

**Comment by alfbr** [comment]
Please confirm.

**Comment by elila** [comment]
Fixed!
