### ISSUE TITLE
Missing button for <use-absolute-elastic-parameters> tag

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#13]
In the "Prior Model" tab there should be a button for "Use absolute elastic parameters" (together with "Use Vs for facies probability" and "Use sampled inversion logs instead of filtered well logs for facies probability"). The tag is available in the xml-tree, but there is no button for it in the GUI.

**Comment by alfbr** [comment]
Please confirm fix.

**Comment by elila** [comment]
Confirmed
