### ISSUE TITLE
Wavelet format set by default, but not wavelet output - CRAVA will not run

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#15]
There are two settings for wavelets, format and which wavelets to output. If a format is specified without requesting a type of wavelet, CRAVA will not run. The default is to request a wavelet format, but no output wavelet, which fails.

If a wavelet format, e.g. JASON, is unchecked, the GUI will create a model file with "no" for the tag `<jason>`. If no is chosen for all formats, no wavelet will be written to file even if they are requested under output.

CRAVA has sensible default values if there is no information about the formats, so the default should be not to request a format and that this leads to no `<format>` tag in the model file.

To be more specific, this is the default in the GUI:
```
<wavelet-output>
<format>
<jason>yes</jason>
<norsar>no</norsar>
</format>
</wavelet-output>
```
which crashes since we ask for a format without specifying an output.

This is what it looks like if we uncheck both the format boxes and ask for output of well wavelets:
```
<wavelet-output>
<format>
<jason>no</jason>
<norsar>no</norsar>
</format>
<well-wavelets>yes</well-wavelets>
</wavelet-output>
```
which will run, but won't output a wavelet since we say no to both formats.

This is how I want it to look if both format boxes are unchecked:
```
<wavelet-output>
<well-wavelets>yes</well-wavelets>
</wavelet-output>
```
The default in the GUI should also be to have both boxes unchecked.

**Comment by alfbr** [comment]
Please confirm fix.

**Comment by alfbr** [comment]
Please check again (needs new jenkins build).

**Comment by elila** [comment]
Fixed
