### ISSUE TITLE
Tags for controlling vp-vs-ratio not available in estimation mode

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#17]
In estimation mode: The tags `<vp-vs-ratio-from-wells>` and `<vp-vs-ratio>` should be possible to control under "Setting". The tags are available in prediction mode.

**Comment by alfbr** [comment]
Please confirm fix.

**Comment by elila** [comment]
I see the buttons in Settings, but they do not work as intended. Stuck on <vp-vs-ratio-from-wells>.

**Comment by alfbr** [comment]
Please check again.

**Comment by elila** [comment]
Fixed
