### ISSUE TITLE
Surface uncertainty Multizone background model

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#20]
The surface uncertainty of the base surface of the lowest zone need to be zero, and the GUI is coded such that you cannot change the surface uncertainty of the lowest zone. The problem is that every time you add a new zone you may want to finish this zone before creating a new one, but you cannot change the surface uncertainty before you add a new zone.

**Comment by alfbr** [comment]
This should be fixed now, please reopen if not.
