### ISSUE TITLE
Changing the "Apply to all stacks" button

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#24]
The "Apply to all stacks" button should only apply to the "User defined" "Header format information (in the "Survey information" tab).

I suggest moving the button underneath "Ignore coordinate scaling" and it should only be visible when "User defined" is chosen.

The button should be renamed "Apply format to all stacks" and only change "Inline", "Crossline", "x-coordinate", "y-coordinate" and "Ignore coordinate scaling" for all stacks.

**Comment by alfbr** [comment]
Please confirm fix.

**Comment by elila** [comment]
Button should say "Apply format to all stacks", now says "Apply to format all stacks".

When adding a new stack, red frames show up around the fields Crossline, x-coordinate and y-coordinate information (new issue).

**Comment by alfbr** [comment]
Please check again.

**Comment by elila** [comment]
Fixed
