### ISSUE TITLE
The Local Noise button does not work properly

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#25]
When opening a previous project the "Local noise" button appeares ticked when it's not supposed to (the xml-tree has the correct value, though.)

If the Local Noise button is ticked, the "Estimate Local Noise" button needs to be unticked and ticked for the change to take effect.

**Comment by alfbr** [comment]
I am not able to reproduce this behaviour. Local noise button remains unticked when opening a project where it is supposed to be unticked.
