### ISSUE TITLE
<time-value> not read on import of model file

### ISSUE THREAD

**Issue by elila** [CRAVA/cravagui#53]
When reading in a model file using File -> Open, tags `<time-value>` under `<interval-two-surfaces>` are not read.

Seems to be read correctly from 'Open previous project'.

**Comment by alfbr** [comment]
Please give a more detailed description, e.g., what time-value?

**Comment by elila** [comment]
Ok now? Tags disappeared when posting.

**Comment by alfbr** [comment]
I don't understand, are you able to reproduce the issue?

**Comment by alfbr** [comment]
Please confirm

**Comment by elila** [comment]
Confirmed
