### ISSUE TITLE
New tags for wavelet-estimation-interval

### ISSUE THREAD

**Issue by alfbr** [CRAVA/cravagui#80]
Previously we had:
```
<wavelet-estimation-interval>
<top-surface-file> surface.txt </top-surface-file>
</wavelet-estimation-interval>
```
With the support of constant time surfaces, this should now look like:
```
<wavelet-estimation-interval>
   <top-surface>
       <time-file>  surface.txt </time-file>
  </top-surface>

<wavelet-estimation-interval>
 <top-surface>
       <time-value>  1500 </time-value>
 </top-surface>

```
 The gui needs to be updated accordingly.

**Comment by hgolsen** [comment]
This is change is also added for estimation intervals under facies probabilites, the new setup is

<facies-probabilities>
  <estimation-interval>
   <top-surface>
     <time-file> surface.txt </time-file>
   </top-surface>

or

<facies-probabilities>
  <estimation-interval>
   <top-surface>
     <time-value> 1500 </time-value>
   </top-surface>

**Comment by alfbr** [comment]
All functionality related to this issue is now implemented. Will close issue after initial testing.
